package constants

import "time"

// Challenge States
const (
	CHALLENGE_OPEN      = "CHALLENGEOPEN"
	CHALLENGE_STARTED   = "CHALLENGESTARTED"
	CHALLENGE_ENDED     = "CHALLENGEENDED"
	CHALLENGE_ABANDON   = "CHALLENGEABANDON"
)

// WebSocket Events
const (
	PING_SERVER             = "PING_SERVER"
	USER_JOINED             = "USER_JOINED"
	USER_LEFT               = "USER_LEFT"
	CREATOR_ABANDON         = "CREATOR_ABANDON"
	WS_CHALLENGE_STARTED    = "CHALLENGE_STARTED"
	OWNER_LEFT              = "OWNER_LEFT"
	OWNER_JOINED            = "OWNER_JOINED"
	NEW_OWNER_ASSIGNED      = "NEW_OWNER_ASSIGNED"
	JOIN_CHALLENGE          = "JOIN_CHALLENGE"
	RETRIEVE_CHALLENGE      = "RETRIEVE_CHALLENGE"
	LEADERBOARD_UPDATE      = "LEADERBOARD_UPDATE"
	PUSH_SUBMISSION         = "PUSHSUBMISSION"
	CURRENT_LEADERBOARD     = "CURRENT_LEADERBOARD"
	GAME_FINISHED           = "GAME_FINISHED"
	CHAT_MESSAGE            = "CHAT_MESSAGE"
	GET_ALL_CHALLENGES      = "GET_ALL_CHALLENGES"
	GET_CHALLENGE_DATA      = "GET_CHALLENGE_DATA"
	GET_CHALLENGE_MIN       = "GET_CHALLENGE_MIN"
	GET_PARTICIPANT_DATA    = "GET_PARTICIPANT_DATA"
	GET_PARTICIPANTS_DATA   = "GET_PARTICIPANTS_DATA"
	GET_NOTIFICATIONS       = "GET_NOTIFICATIONS"
	WHOLE_CHAT              = "WHOLECHAT"
	SEND_MESSAGE            = "SENDMESSAGE"
	PUSH_NEW_CHAT           = "PUSHNEWCHAT"
	ACCEPT_NEW_NOTIFICATION = "ACCEPTNEWNOTIFICATION"
	PUSH_NEW_NOTIFICATION   = "PUSHNEWNOTIFICATION"
	WHOLE_NOTIFICATION      = "WHOLENOTIFICATION"
	WHOLE_LEADERBOARD       = "WHOLELEADERBOARD"
	NEW_SUBMISSION          = "NEW_SUBMISSION"
)

const (
	BufferTime = 10 * time.Minute
)
